stages:
  - build
  - test
  - publish

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - java
    - gradle
  script:
    - ./gradlew build publishToMavenLocal -x signArchives


publish:
  stage: publish
  tags:
    - java
    - gradle
  script:
    - ./gradlew generatePomFileForMavenJavaPublication publish -x signArchives
  only:
    - tags
